
DROP TABLE IF EXISTS VILLAINS
DROP TABLE IF EXISTS HEROES
DROP TABLE IF EXISTS GAME

CREATE TABLE GAME(
    [DateTime] DateTime PRIMARY KEY,
    OUTCOME NVARCHAR(1) CHECK(OUTCOME IN ('W','L'))
)

CREATE TABLE HEROES(
    CharacterName NVARCHAR(100),
    MAXDAMAGE INT NOT NULL, 
    MINDAMAGE INT NOT NULL,
    ROLLS INT NOT NULL,
    hID NVARCHAR(10) PRIMARY KEY
)

CREATE TABLE VILLAINS(
    VillanName NVARCHAR(100),
    HP INT,
    vID NVARCHAR(10) PRIMARY KEY
)


SELECT 
    *
FROM
    information_schema.tables;