DROP TABLE IF EXISTS ATTACK
DROP TABLE IF EXISTS VILLAN
DROP TABLE IF EXISTS [CHARACTER]
DROP TABLE IF EXISTS GAME

CREATE TABLE GAME(
    [DateTime] DATE PRIMARY KEY,
    OUTCOME NVARCHAR(1) CHECK(OUTCOME IN ('W','L'))
)

CREATE TABLE [CHARACTER](
    CharacterName NVARCHAR(100),
    MAXDAMAGE INT NOT NULL, 
    MINDAMAGE INT NOT NULL,
    ROLLS INT NOT NULL,
    cID INT PRIMARY KEY
)

CREATE TABLE VILLAN(
    VillanName NVARCHAR(100),
    HP INT,
    vID INT PRIMARY KEY
)

CREATE TABLE ATTACK(
    AttackCount INT, 
    [DateTime] DATE,
    Damage INT NOT NULL, 
    cID INT,
    vID INT,
    CONSTRAINT FK_CharID FOREIGN KEY (cID) REFERENCES [CHARACTER](cID),
    CONSTRAINT FK_VillanID FOREIGN KEY (vID) REFERENCES Villan(vID),
    CONSTRAINT FK_DateTime FOREIGN KEY ([DateTime]) REFERENCES GAME([DateTime]),
    CONSTRAINT CK_Attack_ PRIMARY KEY (AttackCount,[DateTIme])
)

