DROP TABLE IF EXISTS ATTACK
DROP TABLE IF EXISTS VILLAN
DROP TABLE IF EXISTS [CHARACTER]
DROP TABLE IF EXISTS GAME

CREATE TABLE GAME(
    [DateTime] DATE PRIMARY KEY,
    OUTCOME BOOLEAN
)

CREATE TABLE [CHARACTER](
    CharacterName NVARCHAR(100) PRIMARY KEY,
    MAXDAMAGE INT NOT NULL, 
    MINDAMAGE INT NOT NULL,
    ROLLS INT NOT NULL
)

CREATE TABLE VILLAN(
    VillanName NVARCHAR(100) PRIMARY KEY,
    HP INT
)

CREATE TABLE ATTACK(
    AttackCount INT, 
    [DateTime] DATE,
    Damage INT NOT NULL, 
    CharacterName NVARCHAR(100),
    VillanName NVARCHAR(100),
    CONSTRAINT FK_CharacterName FOREIGN KEY (CharacterName) REFERENCES [CHARACTER](CharacterName),
    CONSTRAINT FK_VillanName FOREIGN KEY (VillanName) REFERENCES Villan(VillanName),
    CONSTRAINT FK_DateTime FOREIGN KEY ([DateTime]) REFERENCES GAME([DateTime]),
    CONSTRAINT CK_Attack_ PRIMARY KEY (AttackCount,[DateTIme])
)