INSERT INTO [CHARACTER] VALUES('Captain Swinburne',6,1,2,1)
INSERT INTO [CHARACTER] VALUES ('Rick', 10,4,2,2)

INSERT INTO VILLAN VALUES('FaceBook',1,1)
INSERT INTO VILLAN VALUES('Management Man',1,2)
INSERT INTO VILLAN VALUES('Covid Cal',1,3)
INSERT INTO VILLAN VALUES('Networking Nancy',1,4)


Select * From VILLAN
SELECT * FROM [CHARACTER]